"""
Observability layer, structured logging with trace correlation.

Every log line carries the trace_id generated by the Go gateway.
This means a single request can be followed across both services
by grepping one UUID
"""
import time
import json
from dataclasses import dataclass, asdict
from utils.create_logger import get_logger

logger = get_logger(__name__)


@dataclass
class EvalTrace:
    """
    Immutable record of one prompt evaluation event.
    Written to the log as structured JSON so it can be
    ingested by any log aggregator (ELK, Loki, CloudWatch).
    """
    trace_id: str
    task: str
    backend: str
    winner: str
    reachability_a: float
    reachability_b: float
    score_a: float
    score_b: float
    latency_a_ms: float
    latency_b_ms: float
    variant_a: str
    variant_b: str
    # ISO 27001: record when the event occurred, not just that it occurred
    timestamp: str = ""

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def log_eval(trace: EvalTrace) -> None:
    """
    Writes a structured JSON trace line to the log.
    One line per evaluation — machine readable, human scannable.
    """
    logger.info(json.dumps(asdict(trace)))


def reachability_gap_report(
    trace_id: str,
    reachability_a: float,
    reachability_b: float,
    winner: str,
    baseline: float = 0.97,
) -> str:
    """
    Generates a plain-language explanation of the controllability gap.
    This is Option C from the roadmap — the Minsky framing made
    visible to the caller so they understand not just *which* prompt
    won but *why* and *how much room for improvement remains*.

    baseline: the paper's theoretical upper bound (0.97 for ≤10-token prompts).
    """
    winner_reach = reachability_a if winner == "a" else reachability_b
    loser_reach = reachability_b if winner == "a" else reachability_a
    gap_to_baseline = round(baseline - winner_reach, 4)
    gap_between = round(winner_reach - loser_reach, 4)

    lines = [
        f"Winning variant '{winner}' achieved a reachability index of {winner_reach:.4f}.",
        f"The losing variant scored {loser_reach:.4f} — a margin of {gap_between:.4f}.",
    ]

    if gap_to_baseline <= 0.02:
        lines.append(
            "The winning prompt is near the theoretical upper bound (0.97) "
            "from Bhargava et al. — the model is being steered with high precision."
        )
    elif gap_to_baseline <= 0.15:
        lines.append(
            f"There is a {gap_to_baseline:.4f} gap to the theoretical upper bound (0.97). "
            "The optimizer could likely find a tighter prompt through further search."
        )
    else:
        lines.append(
            f"There is a significant {gap_to_baseline:.4f} gap to the theoretical upper bound (0.97). "
            "Neither prompt is controlling the output distribution well. "
            "Consider restructuring the prompt template or switching to a stronger model."
        )

    return " ".join(lines)